#!/bin/sh

# ==========================================
# MibExplorer Script SDK v2
# ==========================================
#
# Purpose:
#   Lightweight helper library for MibExplorer Script Center packages.
#
# Design goals:
#   - Keep scripts simple and readable
#   - Stay QNX-compatible
#   - Avoid GNU-specific tools and assumptions
#   - Standardize logging, path handling, mounts, and common file operations
#
# Important notes:
#   - Script Center already executes scripts in an isolated temporary workspace
#     and normally cleans it automatically.
#   - Files created inside the Script Center working directory usually do NOT
#     need manual cleanup.
#   - If a script writes outside its working directory (for example to SD card,
#     /mnt/app, /mnt/efs-persist, etc.), the script author is responsible for
#     handling cleanup or restoration if needed.
#

# ------------------------------------------
# Standard MIB paths
# ------------------------------------------
#
# These variables provide common paths used by many scripts.
# Scripts may use them directly instead of hardcoding paths.
#
MX_PATH_SWDL_LOG="/net/rcc/mnt/efs-persist/SWDL/Log"
MX_PATH_EFS_PERSIST="/net/rcc/mnt/efs-persist"
MX_PATH_MNT_APP="/net/rcc/mnt/app"

MX_PATH_CFG_ACK_RAND="$MX_PATH_SWDL_LOG/CfgAckRand.z"
MX_PATH_CFG_ACK="$MX_PATH_SWDL_LOG/CfgAck.z"
MX_PATH_SVMINFO="$MX_PATH_SWDL_LOG/SvmInfo.z"
MX_PATH_SVMOLD="$MX_PATH_SWDL_LOG/SvmOld.z"

MX_PATH_VERSION_TXT="/net/rcc/dev/shmem/version.txt"
MX_PATH_SWDL_SVM_TXT="/net/rcc/dev/shmem/SWDL_SVM.txt"

MX_PATH_MODIFY_E2P="/net/rcc/usr/apps/modifyE2P"

# ------------------------------------------
# Logging helpers
# ------------------------------------------

# Print a plain log line.
mx_log() {
    echo "$1"
}

# Print a titled section block to improve readability in Script Center logs.
mx_step() {
    echo "=================================================="
    echo "$1"
    echo "=================================================="
}

# Print an informational message.
mx_info() {
    echo "[INFO] $1"
}

# Print a success message.
mx_ok() {
    echo "[OK] $1"
}

# Print a warning message.
mx_warn() {
    echo "[WARN] $1"
}

# Print an error message.
mx_error() {
    echo "[ERROR] $1"
}

# Print an error and stop the script immediately.
mx_fail() {
    mx_error "$1"
    exit 1
}

# ------------------------------------------
# Validation helpers
# ------------------------------------------

# Ensure that a required file exists.
# Usage:
#   mx_require_file "/path/to/file"
mx_require_file() {
    if [ ! -f "$1" ]; then
        mx_fail "Missing file: $1"
    fi
}

# Ensure that a required executable exists and is executable.
# Usage:
#   mx_require_cmd "/path/to/executable"
mx_require_cmd() {
    if [ ! -x "$1" ]; then
        mx_fail "Missing executable: $1"
    fi
}

# Ensure that a required directory exists.
# Usage:
#   mx_require_dir "/path/to/dir"
mx_require_dir() {
    if [ ! -d "$1" ]; then
        mx_fail "Missing directory: $1"
    fi
}

# Ensure that a file generated by the script now exists.
# Useful after building candidates or temporary outputs.
# Usage:
#   mx_require_generated "/tmp/work/CfgAck_candidate.z"
mx_require_generated() {
    if [ ! -f "$1" ]; then
        mx_fail "Expected generated file missing: $1"
    fi
}

# ------------------------------------------
# SD helpers
# ------------------------------------------

# Detect the first available SD root.
# Returns:
#   /net/mmx/fs/sda0 or /net/mmx/fs/sdb0
# Exit code:
#   0 if found, 1 if not found
mx_find_sd() {
    if [ -d /net/mmx/fs/sda0 ]; then
        echo /net/mmx/fs/sda0
        return 0
    fi
    if [ -d /net/mmx/fs/sdb0 ]; then
        echo /net/mmx/fs/sdb0
        return 0
    fi
    return 1
}

# Return the SD root or fail immediately if no SD is present.
# Usage:
#   SD_ROOT=`mx_require_sd`
mx_require_sd() {
    SD_ROOT=`mx_find_sd` || mx_fail "No SD card found"
    echo "$SD_ROOT"
}

# Remount the given SD root read-write.
# Usage:
#   mx_mount_sd_rw "$SD_ROOT"
mx_mount_sd_rw() {
    mount -uw "$1" 2>/dev/null || true
}

# Remount the given SD root read-only.
# Usage:
#   mx_mount_sd_ro "$SD_ROOT"
mx_mount_sd_ro() {
    mount -ur "$1" 2>/dev/null || true
}

# ------------------------------------------
# Standard MIB mount helpers
# ------------------------------------------

# Remount efs-persist read-write.
# Useful when a script needs to write into /net/rcc/mnt/efs-persist.
mx_mount_efs_rw() {
    mount -uw "$MX_PATH_EFS_PERSIST" 2>/dev/null || true
}

# Remount efs-persist read-only.
mx_mount_efs_ro() {
    mount -ur "$MX_PATH_EFS_PERSIST" 2>/dev/null || true
}

# Remount /mnt/app read-write.
# Useful only for scripts that intentionally modify /mnt/app content.
mx_mount_app_rw() {
    mount -uw "$MX_PATH_MNT_APP" 2>/dev/null || true
}

# Remount /mnt/app read-only.
mx_mount_app_ro() {
    mount -ur "$MX_PATH_MNT_APP" 2>/dev/null || true
}

# Run a sync command quietly.
# Useful after file replacement or before remounting read-only.
mx_sync() {
    sync 2>/dev/null || true
}

# ------------------------------------------
# Directory / file helpers
# ------------------------------------------

# Create a directory if needed, without failing on existing directory.
# Usage:
#   mx_safe_mkdir "/path/to/output"
mx_safe_mkdir() {
    mkdir -p "$1" 2>/dev/null || true
}

# Copy a file if it exists, otherwise log a [MISS].
# Destination should be a file path or existing directory target path.
# Usage:
#   mx_copy_if_exists "/src/file" "/dst/file"
mx_copy_if_exists() {
    SRC="$1"
    DST="$2"

    if [ -f "$SRC" ]; then
        if cp "$SRC" "$DST" 2>/dev/null; then
            mx_ok "copied: $SRC"
        else
            mx_error "copy failed: $SRC"
            return 1
        fi
    else
        mx_warn "missing: $SRC"
        return 1
    fi

    return 0
}

# Copy a file into a directory using its original basename.
# Usage:
#   mx_copy_to_dir_if_exists "/src/file" "/dst/dir"
mx_copy_to_dir_if_exists() {
    SRC="$1"
    DST_DIR="$2"

    if [ -f "$SRC" ]; then
        BASENAME=`basename "$SRC"`
        if cp "$SRC" "$DST_DIR/$BASENAME" 2>/dev/null; then
            mx_ok "copied: $SRC -> $DST_DIR/$BASENAME"
        else
            mx_error "copy failed: $SRC"
            return 1
        fi
    else
        mx_warn "missing: $SRC"
        return 1
    fi

    return 0
}

# Backup a file into a backup directory using its basename.
# This is useful before replacing a real MIB file.
# Usage:
#   mx_backup_file "$MX_PATH_CFG_ACK" "$BACKUP_DIR"
mx_backup_file() {
    SRC="$1"
    BACKUP_DIR="$2"

    mx_safe_mkdir "$BACKUP_DIR"

    if [ -f "$SRC" ]; then
        BASENAME=`basename "$SRC"`
        if cp "$SRC" "$BACKUP_DIR/$BASENAME" 2>/dev/null; then
            mx_ok "backup created: $SRC"
        else
            mx_fail "backup failed: $SRC"
        fi
    else
        mx_warn "backup skipped, file missing: $SRC"
    fi
}

# Replace a destination file with a source file.
# This helper is intentionally simple and explicit.
# Usage:
#   mx_replace_file "/tmp/CfgAck_candidate.z" "$MX_PATH_CFG_ACK"
mx_replace_file() {
    SRC="$1"
    DST="$2"

    mx_require_file "$SRC"

    if cp "$SRC" "$DST" 2>/dev/null; then
        mx_ok "replaced: $DST"
    else
        mx_fail "replace failed: $DST"
    fi
}

# ------------------------------------------
# Cleanup helpers
# ------------------------------------------
#
# Script Center already handles temporary workspace cleanup.
# These helpers are mainly for:
#   - restoring mounts to read-only
#   - cleaning files created OUTSIDE the workspace if needed
#

MX_CLEANUP_ACTIONS=""

# Register a cleanup shell command to be executed later.
# Cleanup commands are executed in reverse registration order.
# Usage:
#   mx_register_cleanup "mx_mount_efs_ro"
#   mx_register_cleanup "rm -f /net/mmx/fs/sda0/MyDump/temp.bin"
mx_register_cleanup() {
    if [ -z "$MX_CLEANUP_ACTIONS" ]; then
        MX_CLEANUP_ACTIONS="$1"
    else
        MX_CLEANUP_ACTIONS="$1
$MX_CLEANUP_ACTIONS"
    fi
}

# Execute all registered cleanup commands.
# Usually called from a trap.
mx_run_cleanups() {
    OLD_IFS="$IFS"
    IFS='
'
    for ACTION in $MX_CLEANUP_ACTIONS
    do
        if [ -n "$ACTION" ]; then
            sh -c "$ACTION" 2>/dev/null || true
        fi
    done
    IFS="$OLD_IFS"
}

# Install a default cleanup trap that executes registered cleanup commands.
# Usage:
#   mx_enable_cleanup_trap
mx_enable_cleanup_trap() {
    trap 'mx_run_cleanups' EXIT
}

# Register a standard "restore read-only" cleanup for efs-persist.
mx_cleanup_restore_efs_ro() {
    mx_register_cleanup "mx_mount_efs_ro"
}

# Register a standard "restore read-only" cleanup for /mnt/app.
mx_cleanup_restore_app_ro() {
    mx_register_cleanup "mx_mount_app_ro"
}

# Register a standard "restore read-only" cleanup for SD root.
# Usage:
#   mx_cleanup_restore_sd_ro "$SD_ROOT"
mx_cleanup_restore_sd_ro() {
    mx_register_cleanup "mx_mount_sd_ro \"$1\""
}

# ------------------------------------------
# Built-in action helpers
# ------------------------------------------

# Call modifyE2P using the exact command style already validated in MibExplorer.
# Usage:
#   mx_apply_e2p
mx_apply_e2p() {
    mx_require_cmd "$MX_PATH_MODIFY_E2P"
    on -f rcc "$MX_PATH_MODIFY_E2P" w 3f0 00 00 01
}

# Prepare a standard export directory on SD.
# Usage:
#   EXPORT_DIR=`mx_prepare_export_dir "$SD_ROOT" "MyScriptExport"`
mx_prepare_export_dir() {
    SD_ROOT="$1"
    NAME="$2"
    OUT_DIR="$SD_ROOT/$NAME"

    mx_safe_mkdir "$OUT_DIR"
    echo "$OUT_DIR"
}