#!/bin/sh

# Type: ReadOnly
# Version: 1.0.0
# Author: MibExplorer Team
# Example package entry point for Script Center
# You can put until 3 Lines of commented text
# Those 3 lines will be displayed in the Script Center as a description of the script

echo "=== Exemple package start ==="
echo "Working directory:"
pwd

echo "Running helper script..."
sh ./scripts/helper.sh

echo "Reading package data file..."
cat ./data/message.txt

echo "Writing a temporary package output file..."
echo "generated by package Exemple" > /tmp/mibexplorer_exemple/output.txt

echo "Listing the package output file..."
ls -l /tmp/mibexplorer_exemple/output.txt

echo "Waiting a moment so the user can observe the execution log / throbber..."
sleep 2

echo "Cleaning up..."
rm -f /tmp/mibexplorer_exemple/output.txt

echo "=== Exemple package end ==="
exit 0
